### ISSUE TITLE
CPT identifier is identical to f(x) Updater plugin

### ISSUE THREAD

**Issue by johnalarcon** [codepotent/Update-Manager#1]
The Update Manager plugin uses a CPT identifier `plugin_repo` that is used by another updater plugin. While this doesn't cause any catastrophic errors, it should be corrected.

## Expected behavior
Unique CPT identifier to avoid any confusion.

## Current behavior
If the f(x) Updater was previously installed and then the Update Manager is later installed, it will pick up on any orphaned entries and leave the user wondering where they came from when they see a list of entries right after installation. This is confusing and not a great user experience.

## Possible solution
Changing the CPT identifier will be a painless solution. The identifier is [defined](https://github.com/codepotent/update-manager/blob/4c8872f33f58af92b7adba76cc3e700c8174b955/includes/constants.php#L88) as a constant, so, it's just one quick edit. 

## Context
When getting started with the remote update process, I had the f(x) Updater plugin installed and had created a bunch of entries. When I decided to write my own plugin for remote updates, I had all those entries already in the database, so, I just mirrored my plugin's CPT to pull those in and save some work. Ha.

H/T: [ozfiddler](https://github.com/ozfiddler)

**Comment by ginsterbusch** [comment]
I'd suggest adding a `if( !defined('...')` test, so one may define the constant on the fly.

**Comment by johnalarcon** [comment]
Allowing users to do this themselves could create support issues, particularly for those who don't have experience with namespaces (or reading docs.) I'm going to go with the proposed solution of changing the identifier and leaving it defined as an internal constant; it's an easy fix, doesn't require any new docs, and won't see any tickets opened about it. :)
