### ISSUE TITLE
Make it possible to store the images in different locations

### ISSUE THREAD

**Issue by simplycomputing** [codepotent/Update-Manager#12]
# Description
The location for the images required in the updating windows is hard-coded in the UpdateClient.class.php file as a folder called images directly inside the plugin folder. Many plugins already have an images folder, typically as a sub-folder in assets. This is actually a more logical place to store them. I suggest this be made more versatile to allow users to set the location that best suits their plugins. 

# Context
This will make the plugin more adaptable for the different approaches used by developers. It will also stop people (like me) messing with the code.

**Comment by johnalarcon** [comment]
While I disagree that an `assets` directory is a more logical location than an `images` directory in the case of 99% of ClassicPress/WordPress plugins, your point is well-taken. I'll take a look into this.

**Comment by johnalarcon** [comment]
For reference, these are [the lines in question](https://github.com/codepotent/Update-Manager/blob/af8aaec4d0f5458c70619e8ac3d71bc5c82a5d58/classes/UpdateClient.class.php#L555-L557).

**Comment by simplycomputing** [comment]
I don't pretend to be any sort of expert on plugin file structure. I was just going by WooCommerce (and hence Classic Commerce) which already has an images folder in place. I needed to change those lines to not end up with images in two different places.

**Comment by johnalarcon** [comment]
All good. In fact, Woo is exactly the kind of plugin where it might make more sense for an assets directory due to its sheer size. The filter you're suggesting will make the Update Manager more versatile; it will definitely be a nice addition.
