### ISSUE TITLE
Hooks names different from documentation

### ISSUE THREAD

**Issue by xxsimoxx** [codepotent/Update-Manager#13]
# Description 
For example to filter the request you have to hook to `Update_Manager_filter_request` but in the [documentation](https://codepotent.com/classicpress/plugins/update-manager/#docs-filters) is written `codepotent_update_manager_filter_request`.

**Comment by johnalarcon** [comment]
I have verified that the filter works as expected; the documentation depicts the correct hook. The following contrived example demonstrates.

```
add_filter('codepotent_update_manager_filter_request', 'intercept_request');
function intercept_request($request) {
	set_transient('request_'.time(), $request, 300);
	return $request;
}
```

Perhaps you have edited core Update Manager files such as `constants.php` or `functions.php`.

**Comment by xxsimoxx** [comment]
No, but I haven't downloaded the release. I've forked the master branch.
Just now I was having some trouble with PLUGIN_FILENAME, and the problem was the directory name of the plugin (`Update-Manager` if cloning from Git).
So my error, sorry!
