### ISSUE TITLE
Incorrect function used for translation

### ISSUE THREAD

**Issue by xxsimoxx** [codepotent/Update-Manager#22]
# Description 
This [line](https://github.com/codepotent/Update-Manager/blob/6f540b7697f0c74870f3270dea53276bb263c383/classes/UpdateClient.class.php#L337) I think that should be

`$anchor_text = esc_html__('View details', 'codepotent-update-manager');`
and not
`$anchor_text = esc_html('View details', 'codepotent-update-manager');`

With or without text domain (issue https://github.com/codepotent/Update-Manager/issues/21).

**Comment by johnalarcon** [comment]
Thanks!
