### ISSUE TITLE
Adding a filter to deal with opt-out and privacy

### ISSUE THREAD

**Issue by xxsimoxx** [codepotent/Update-Manager#29]
# Description
Add a filter about [here](https://github.com/codepotent/Update-Manager/blob/1b0552d146eea55c5b802aebe4ce2d65ae0e0cdb/classes/UpdateClient.class.php#L494) to filter `$body`.

# Context
**It would be interesting to have a way to let the UpdateClient class to communicate with Update Manager passing extra information.**
The idea (but this feature request extend it to other possible needs) is to deal with a plugin that allow site admin to opt-out for stats:
see xxsimoxx/stats-for-update-manager#15, ClassicPress-research/classic-commerce#166.
This way the developer can add a filter to pass extra arguments, like `$body['sfum']='no-log'`, that can be handled by UM, SFUM or other companion plugins.

**Comment by johnalarcon** [comment]
The Update Manager plugin doesn't collect data, so, it's the wrong place to add code to allow uses to opt out. This should be handled in the Stats extension as it introduced the functionality.

However, if a user wants to opt out of data collection, the developer would still have to log their URL in some way (and in plaintext) so, simply by opting out, they would be tracked. In other words, this isn't a viable request. It is an _everyone or no one_ situation: either everyone is tracked (via hashed URLs) or no one is tracked (by not using the Stats extension.)
