### ISSUE TITLE
Error when php tags in Plugin Details

### ISSUE THREAD

**Issue by azurecurve** [codepotent/Update-Manager#32]
# Description 
A section of code in the plugin Details section causes a corrupted version to be saved.

# Steps to Reproduce
1. Create new plugin endpoint.
2. Enter plugin details contain code similar to this:
```
<?php
	if (function_exists('azrcrv_urls_get_custom_shortlink')){
		printf(' %s', ''.'Shortlink'.'');
	}
	?>
```
3. Click Update
4. See corrupted plugin details.

# Expected Behavior
Plugin Details should save as entered.

# Screenshots
![image](https://user-images.githubusercontent.com/46169890/73283219-1269bf80-41f3-11ea-933b-c19503ddf547.png)

# Environment
Under which type of environment did you experience this problem?

**Desktop**
 - Operating System: Windows 10
 - Browser & Version: Vivaldi 2.10.1745.27 (Stable channel) (64-bit)

**Comment by johnalarcon** [comment]
I'll get this updated to strip PHP tags. Thanks for the report.

**Comment by johnalarcon** [comment]
PHP tags are now stripped from the input and a note added to the interface.
