### ISSUE TITLE
Plugin Details lost if Endpoint Identifier not set

### ISSUE THREAD

**Issue by azurecurve** [codepotent/Update-Manager#33]
# Description 
When creating a new plugin endpoint, if you omit the endpoint Identifier the Plugin Details are lost when saving.

# Steps to Reproduce
1. Create a new plugin endpoint.
2. Enter a name.
3. Leave the Endpoint Identifier blank.
4. Enter Plugin Details.
5. Hit Update.
6. See blank Plugin Details.

# Expected Behavior
Plugin Details should be retained and an error presented.

# Environment
Under which type of environment did you experience this problem?

**Desktop**
 - Operating System: Windows 10
 - Browser & Version: Vivaldi 2.10.1745.27 (Stable channel) (64-bit)

**Comment by johnalarcon** [comment]
The identifier is the glue that holds a given record together; without it, there's no way to associate the data. So, I'm leaning toward disabling the update/publish operation (via JS) until the identifier field is populated. I'll think on it. Thanks for the report.

**Comment by johnalarcon** [comment]
Endpoints can no longer be saved without an identifier; the buttons are disabled until that field is populated.
