### ISSUE TITLE
Deploying a plugin without first creating an endpoint can lead to delays

### ISSUE THREAD

**Issue by azurecurve** [codepotent/Update-Manager#36]
# Description 
If a plugin is loaded to a site when an endpoint hasn't been created the plugins page is very slow to load. However, it currently takes approx. 40 seconds to load.

# Steps to Reproduce
1. Create plugin integrated with update client.
2. Upload to site.
3. Load plugins page.

# Expected Behavior
The plugins page should load in a reasonable time.

# Environment
Under which type of environment did you experience this problem?

**Desktop**
 - Operating System: Windows 10
 - Browser & Version: Vivaldi 2.10

**Comment by johnalarcon** [comment]
Per our conversation on Slack, I'll reduce the timeout to 3-5 seconds (down from 20) and make the value filterable, just in case anyone wants a longer or shorter timeout period. Thanks for reporting this.

**Comment by johnalarcon** [comment]
I've taken the timeout period down to 5 seconds (the default value) and implemented a filter `codepotent_update_manager_timeout` for those who wish to alter the value for their own installations. This change has been implemented in `UpdateClient.class.php`.

An additional performance improvement has also been implemented in #37. Both of these improvements will be rolled out in version 2.0.0. Let me know how these changes impact your experience.
