### ISSUE TITLE
Constants in UpdateClient.class.php

### ISSUE THREAD

**Issue by xxsimoxx** [codepotent/Update-Manager#39]
# Description 
Constants will be undefined when the class is used alone.
`PLUGIN_PREFIX` is used [here](https://github.com/codepotent/Update-Manager/blob/8d897deb4ed03db594eef9ba557dcbac788d16b7/classes/UpdateClient.class.php#L651) and [here](https://github.com/codepotent/Update-Manager/blob/8d897deb4ed03db594eef9ba557dcbac788d16b7/classes/UpdateClient.class.php#L689)

# Additional Context
It is just related to milestone 2.0.0 branch.

**Comment by johnalarcon** [comment]
Fixed on the milestone branch. Thanks for the report!
