### ISSUE TITLE
UpdateClient.class.php not working in main plugin dir

### ISSUE THREAD

**Issue by xxsimoxx** [codepotent/Update-Manager#4]
### Bug Description
Class don't work if it is located in the root dir 
### Steps to Reproduce
```php
require_once( 'inc/UpdateClient.class.php' );
require_once( 'UpdateClient.class.php' );
```
Returns an error (so I know both are loaded)
```php
require_once( 'UpdateClient.class.php' );
```
No errors, no warnings, just the plugin don't report available updates.
```php
require_once( '/inc/subdir/UpdateClient.class.php' );
```
No errors, no warnings, just the plugin don't report available updates.
### Expected Behavior
```php
require_once( 'inc/UpdateClient.class.php' );
```
Works

### Context
Same server, PHP 7.3

### Possible workaround
Line 76 depends on where the file is
`'id' => basename(dirname(__DIR__)).'/'.basename(dirname(__DIR__)).'.php'`

**Comment by johnalarcon** [comment]
On the forums where you originally reported, I indicated that my testing showed that the file could be placed in the root with success. I was looking at a completely different test plugin than the one in which I'd moved the file. Maybe I didn't need 8 test plugins. 🤐  Confirming this is a legitimate issue. While I didn't necessarily think anyone would put such a file in the root of a plugin, the intention was to allow it to run from anywhere, so, this is on my radar for repair. Thanks for following up.

**Comment by johnalarcon** [comment]
If you're interested in testing, add the following method to the class, and then amend the line in the constructor to be `'id' => $this->get_plugin_identifier(),` - I tested this with the update class renamed and stored at the root (and then 3 levels deep.) I believe this sorts the issue and I'll plan on getting it into the next release.

```
private function get_plugin_identifier() {
	include_once(ABSPATH.'/wp-admin/includes/plugin.php');
	$slash = DIRECTORY_SEPARATOR;
	$slashes = ['\\', '/'];
	$dir = explode($slash, str_replace($slashes, $slash, WP_PLUGIN_DIR));
	$file = explode($slash, str_replace($slashes, $slash, __FILE__));
	$diff = array_diff($file, $dir);
	$dir_name = array_shift($diff);
	$identifier = '';
	foreach (array_keys(get_plugins()) as $id) {
		if (strpos($id, $dir_name.DIRECTORY_SEPARATOR) === 0) {
			$identifier = $id;
		}
	}
	return $identifier;
}
```

**Comment by xxsimoxx** [comment]
Tested `get_plugin_identifier()` and works:
- in the root dir
- in a sub sub dir
- when a plugin is myoldname/mynewname.php
Good 👍

**Comment by johnalarcon** [comment]
I found cases where that method would still break, so, I've updated the fix a bit. I'll be adding it to the dev branch shortly. Thanks for your report and testing.
