### ISSUE TITLE
Add version number and updated date to admin list tables

### ISSUE THREAD

**Issue by azurecurve** [codepotent/Update-Manager#41]
# Description
When viewing the list of endpoints, the date shown is the Published Date, but it would be (more) useful to have the last edited date visible.

It would also be useful to see the version number.

# Context
See at a glance when a plugin was last updated and the version.

**Comment by johnalarcon** [comment]
Version numbers are implemented in Milestone 2.0.0 which is out as a manual-install release (for testing purposes only). In that version, plugin and theme endpoints show the currently-serving version numbers in the 2nd column. I was torn on linking it to something, like, say, the download package for the given plugin/theme. Let me know your thoughts. Aside: _I did consider adding the download link to the first column along with Edit, Quick Edit, etc... but it seemed too crowded there._ Here's the current iteration:

![image](https://user-images.githubusercontent.com/12477319/75616252-af29c080-5b03-11ea-8192-a15656d4da9f.png)

As for adding the Updated Date, I like the idea. It raises some design questions that will need to be addressed:

1. The column header is too wide as "Last Updated"; would just "Updated" suffice?
1. Does the column need to be sortable?
1. Does the value need to be linked to something?
1. Should this replace the "Publish" date, or, are both dates useful?

Thoughts?

**Comment by johnalarcon** [comment]
After further consideration and testing, I've come up with some answers to the above points.

1. The term **Updated** or **Modified** works.
1. Yes, a date column should be sortable.
1. I can't think of anything relevant. 
1. Yes. A Publish date is essentially meaningless here and replacing it with the last updated date makes more sense.

Aside: I also added a "Status" column (pending/publish/draft) to allow for sorting by those fields, but, removed it as it is is essentially duplicative of the text-link filter menu at the top.

Here's what I ended up with:

![image](https://user-images.githubusercontent.com/12477319/75617692-95927400-5b17-11ea-85f8-217c92160ab8.png)

What do you think?

**Comment by johnalarcon** [comment]
This is implemented on the milestone-2.0.0 branch. Here's what it ended up looking like (along with a few other improvements). I'll push out an RC3 soon, just to be on the safe side since it was a fair bit of code amended.

![image](https://user-images.githubusercontent.com/12477319/75622543-4586d200-5b56-11ea-9c11-371420b3e291.png)
