### ISSUE TITLE
Error with PHP <7

### ISSUE THREAD

**Issue by xxsimoxx** [codepotent/Update-Manager#5]
### Bug Description
The plugin throws an error when used with PHP <7.
It looks like the problem is here (in constants definition)
`define(__NAMESPACE__.'\PLUGIN_DIRNAME', basename(dirname(__FILE__, 2)));`
`dirname` support 2 parameters only from PHP 7.

Here the error log:
```
[Thu Nov 21 14:00:16.265362 2019] [fcgid:warn] [pid 24452:tid 139896653768448] [client 78.134.126.128:49868] mod_fcgid: stderr: PHP Warning:  dirname() expects exactly 1 parameter, 2 given in ...ioni.it/httpdocs/wp-content/plugins/Update-Manager/includes/constants.php on line 48
[Thu Nov 21 14:00:16.267524 2019] [fcgid:warn] [pid 24452:tid 139896653768448] [client 78.134.126.128:49868] mod_fcgid: stderr: PHP Warning:  require_once(...oni.it/httpdocs/wp-content/plugins//includes/functions.php): failed to open stream: No such file or directory in ...ni.it/httpdocs/wp-content/plugins/Update-Manager/codepotent-update-manager.php on line 74
[Thu Nov 21 14:00:16.267540 2019] [fcgid:warn] [pid 24452:tid 139896653768448] [client 78.134.126.128:49868] mod_fcgid: stderr: PHP Fatal error:  require_once(): Failed opening required '...ni.it/httpdocs/wp-content/plugins//includes/functions.php' (include_path='.:/usr/share/pear:/opt/plesk/php/5.6/share/pear') in ...ioni.it/httpdocs/wp-content/plugins/Update-Manager/codepotent-update-manager.php on line 74
```
### Steps to Reproduce
Switch to PHP 5.6

### Possible solution
If just bumping required PHP to 7, please do something like this, because often wp-cli uses PHP 5.6...
```
if ( ! ( defined( 'WP_CLI' ) && WP_CLI ) ) {
	new UpdateManager;
}
```

**Comment by johnalarcon** [comment]
I think the proper solution would be to integrate a PHP-gate that prevents Update Manager from installing on less than PHP 7. PHP 5.6 is a long dead branch and, while it's still around 50% usage, we'll never move the tech forward if we continue to support those dead versions. This was one of the biggest problems in the WordPress ecosystem; supporting old versions to gain market share (and done in the name of backward compatibility) was horrible for the web and site security as a whole. In actuality, PHP 7.1 reaches end of life in 9 days...and PHP 7.2 reaches end of active support in 8 days. See [here](https://www.php.net/supported-versions.php). If we're writing brand new code (as in the case with this project,) we should be building for PHP 7.3, minimum. I think Code Potent may well need to make a new policy and announcement. ;) I'll leave this issue open for the time being, though, as it's a legitimate issue in the plugin's current form.

**Comment by xxsimoxx** [comment]
I'm with you 100%!
But what do you think excluding the class from being created when we are under WP_CLI ?

**Comment by johnalarcon** [comment]
I'm on Windows and rarely ever use CLI tools. Even if you were to submit a PR, I wouldn't even know where to start with testing it. Wouldn't a PHP-gate prevent object creation under WP-CLI?

**Comment by xxsimoxx** [comment]
The "if" statement above does the job. I have tested and works, but can't help with "formal" testing.

**Comment by johnalarcon** [comment]
I wrote a [PHP gate](https://gist.github.com/johnalarcon/aa5edeca200bf7dad4fec347f1b63e41) a couple years back; it's probably still 100% relevant. Linking it here for ease in finding it later.

**Comment by xxsimoxx** [comment]
Ok, I've just tried to wrap things up in __construct, and works.
I'm not going to do a PR because I think you want to style this better...

If we are using WP_CLI code is not parsed, user is warned but plugin is not deactivated.

```php
	// minimum PHP required to run UpdateManager
	private $php_version = '7.0';
	
	// deactivate plugin
	public function deactivate() {
		deactivate_plugins( plugin_basename( __FILE__ ) );
		if ( isset( $_GET['activate'] ) ) {
			unset( $_GET['activate'] );
		}
	}

	// notice deactivation
	public function php_error() {
		?>
		<div class="notice notice-error">
			<p><?php printf( esc_html__( 'Update Manager requires PHP version %s or above.' ), $this->php_version ) ; ?></p>
		</div>
		<?php
	}
	
	public function __construct() {
		if ( version_compare( phpversion(), $this->php_version, '<' ) ) {
			if ( defined( 'WP_CLI' ) && WP_CLI  ) {
				\WP_CLI::warning( sprintf( esc_html_x( 'Update Manager requires PHP version %s or above and so was not loaded this time.', 'wp-cli' ), $this->php_version ) );
			} else {
				// Ok, we are not in wp-cli so warn users and deactivate
				add_action( 'admin_init', [ $this, 'deactivate' ] );
				add_action( 'admin_notices', [ $this, 'php_error' ] );
			}
		} else {
		// Hook everything in!
			$this->init();
		}
	}
```

**Comment by johnalarcon** [comment]
Thanks for taking the time to consider this issue and work out a solution. I've also been working on a couple ideas similar to what you've proposed.

After working and reworking it, I've decided to simply change the offending line in `constants.php` to get the directory name in a different way that doesn't require a second argument to the `dirname()` function. This is a much simpler solution and really falls inline with my "less code means less places for bugs to hide" philosophy. :) Since no other part of the plugin absolutely requires PHP 7, I think this will be a good solution. The following, which I fully accept looks like the algebraic ramblings of a madman, is the proposed amendment to the constant.

```
// Plugin directory name; ie, codepotent-plugin-name
define(__NAMESPACE__.'\PLUGIN_DIRNAME', substr(str_replace(['\\', '/'], '/', dirname(__DIR__)), strrpos(str_replace(['\\', '/'], '/', dirname(__DIR__)), '/')+1));
```

PS, Don't be afraid to submit a PR. I can always edit it after the fact. You should get credit for your efforts. :)

**Comment by xxsimoxx** [comment]
Surely it's the best solution :-) 
Tested and works perfectly!
