### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by xxsimoxx** [codepotent/Update-Manager#6]
### Feature Description
I'd like (I've already done) to get statistics about plugin usage, something very basic at the moment. Have you planned this? 

If not or not in the near future, with one line of code another plugin can handle that.
This is what I've added just before returning in the function `get_request()` in `includes/functions.php`

`$discard_me = apply_filters( 'um-logging', array( 'slug'=>$request["plugin"], 'site'=>$request["site_url"] ) );`

Then I'm using this filter to store data in a table and retrive active installs...

**Comment by johnalarcon** [comment]
I have considered this, yes, although slightly differently. In addition to knowing where the plugins are installed, it would be helpful to know which versions were in use. The thing is: GDPR.

I _think_ it goes against GDPR to just collect the data. I'm not positive that is the case...that's just my "current understanding". Perhaps a forum post would help to clarify. In my estimation, to be compliant, it would require notices, permission granted, opt-out code, and download-my-data controls; this is far more than I've planned for the plugin. However, if it is just a matter of adding the filter and there aren't any GDPR concerns raised by it, I'm happy to add it.

**Comment by xxsimoxx** [comment]
Sure the version could be important too.
I think adding a filter with things you consider useful (and maybe CP/WP and PHP version and locale) could be a good starting point. 
This allows to write a plugin for statistics, and then code can be merged in the main plugin easily.

> Perhaps a forum post would help to clarify.

Sure!

GDPR is (as my consultants states) about people and we are collecting information about sites.
**But** (better to keep safe)  if we store only the hash of the url *I think* we are fully compliant, without loosing anything.

**Comment by xxsimoxx** [comment]
PR is coming to cover a first step... just doing some more tests.
Consideration: if we have to deal with GDPR when storing data we have to take care of the sysadmin managing logs. If the site name is in plain text in the query and as the user-agent, it may appear (in my tests it does) in log files.
So:
- I've removed the site_url from user agent
- Send it out hashed with SHA512
- "Testing Domains" now works with either plain (to support old `UpdateClient.class.php`) and hashed site_url
- Added a `do_action` for handling statistics and hash the site_url if not already.

I've not salted anything because salting client-side will break everything.

If you agree, I can go on with statistics in a separate plugin, so you can push this and other things...
When the plugin is ready it will be easy to add the Class to your plugin.

**Comment by johnalarcon** [comment]
Linking the [forum post](https://forums.classicpress.net/t/tracking-plugin-installations-and-versions/1777) for better visibility.

**Comment by johnalarcon** [comment]
>If the site name is in plain text in the query and as the user-agent, it may appear (in my tests it does) in log files.
I've also found that my security plugin logs the requesting URL.

And thinking about this more carefully, as well as reviewing your PR, I've come across another issue with transmitting URLs and realize that hashing them isn't going to solve anything.

See, when the remote plugin queries for the plugin's data, the remote site's URL _has to be sent_ to the Update Manager plugin in a [readable format](https://github.com/codepotent/Update-Manager/blob/96d47329953e7e480d1ad810b7ec7bb9de3d69fa/classes/UpdateClient.class.php#L390-L399) – that's how Update Manager is able to populate the endpoint with the local URLs (relative to that requesting site) that point to the banners, icons, and screenshots used in that site's modal windows. If the URL is not transmitted, the Update Manager would have to build those URLs based on it's own location and serve those images itself... In other words... it would still be trackable, just in a different way. I don't see any way around this other than to not use images.

At this point, I'm thinking this is going to have to fall under _informed consent_ where end users of remote plugins that use the Update Manager should be notified that the plugin sends it's name and version number and the current URL, transmitted in plaintext, for tracking usage statistics (if a tracking extension is used) as well as its requests being logged to general server logs. Such notification would be done by adding privacy-related functions in the remote plugin.

**Comment by johnalarcon** [comment]
Ok, so, I've decided against hashing the URL, but, have added a filter to the incoming `$request` right before it's returned. I'll leave it to plugin devs to decide how they want to use it...as well as notifying their users of said use.

However, since the Update Manager will require the site URL in the request, I will add an entry to the Privacy page, so that 3rd party devs can have an example of how to update their own privacy policies (if needed) to cover it.

`$request = apply_filters(PLUGIN_PREFIX.'_filter_request', $request);`
