### ISSUE TITLE
I can not activate the plugin

### ISSUE THREAD

**Issue by ali-kianii** [codepotent/Update-Manager#61]
# Description 
Warning: fopen(/home/tarh/public_html/wp-content/plugins/codepotent-update-manager/codepotent-update-manager.php): failed to open stream: No such file or directory in /home/tarh/public_html/wp-includes/functions.php on line 6111

Warning: require_once(/home/tarh/public_html/wp-content/plugins/codepotent-update-manager/includes/functions.php): failed to open stream: No such file or directory in /home/tarh/public_html/wp-content/plugins/Update-Manager-master/codepotent-update-manager.php on line 71

Fatal error: require_once(): Failed opening required '/home/tarh/public_html/wp-content/plugins/codepotent-update-manager/includes/functions.php' (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') in /home/tarh/public_html/wp-content/plugins/Update-Manager-master/codepotent-update-manager.php on line 71

Please help me with these errors

**Comment by johnalarcon** [comment]
Use a release version.

**Comment by ali-kianii** [comment]
Please test and tell me why the plugin does not activate after installation. Thank you
https://4o0.ir/wp-admin
username: 1tarh
password: 1

**Comment by johnalarcon** [comment]
I deleted your previous comment as it irresponsibly included login credentials. See previous comment for the solution. This is not a place for end-user support.
